<Project>
    <PropertyGroup>
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <Import Project="Directory.Build.user" Condition="Exists('Directory.Build.user')" />
</Project>